version: '3.7'
services:
  frontend:
    image: glare-app
    container_name: glare-app
    volumes:
      - /home/glare/glare-app/config.env:/app/.env
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        REPOSITORY_URL: https://github.com/9536240277/glare-app
        BRANCH_NAME: 9724d4b086dd78b388ba4e3e6aa1c0ce6941472c
        EXPOSED_PORT: 3000
    ports:
      - "3000:3000"
    environment:
      env_file: config.env
    networks:
      - appwrite
    stdin_open: true

networks:
    appwrite:
